/*
 * DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
 * All changes done to this file will be lost upon re-running the 'silence createapi' command.
 * If you want to create new API methods, define them in a new file.
 *
 * Silence is built and maintained by the DEAL research group at the University of Seville.
 * You can find us at https://deal.us.es
 */

"use strict";

import { BASE_URL, requestOptions } from './common.js';

const v_votesAPI_auto = {

    /** Gets all entries from 'v_votes' */
    getAll: async function() {
        let response = await axios.get(`${BASE_URL}/v_votes`, requestOptions);
        return response.data;
    },

    getavgValueByPId: async function(photoId){
        let response = await axios.get(`${BASE_URL}/v_votes/${photoId}`, requestOptions);
        return response.data[0];
    },

    deleteThisUserVotes: async function(userId,photoId){
        let response = await axios.delete(`${BASE_URL}/v_votes/${userId}/${photoId}`, requestOptions);
        return response.data;
    }
};

export { v_votesAPI_auto };